### ISSUE TITLE
readme.md library wrapper example

### ISSUE THREAD

**Issue by tmedwards** [ChapelR/tweego-setup#1]
Based on looking at several UMD and CJS+IIFE libraries recently, I'm beginning to think the wrapper intro should be:

```
(function (define, module, exports) {

	/* library code goes here */

}).call(window);
```

# Reasoning

There's a lot of variation in how the  CommonJS checks in non-ES6 module containers are done.  Some check a global `exports`, while others check for `module` then `module.exports`, and some do both.  There doesn't seem to be a lot of consensus among the containers.  Therefore it seems safer to include an undefined `module` in the wrapper as well.

**Comment by ChapelR** [comment]
That makes sense. I'll update the readme.
