### ISSUE TITLE
update css only

### ISSUE THREAD

**Issue by arohman84** [ChapelR/tweego-setup#13]
how to run update css only ? i mean just compile the css not js or twee files. 

right now we already had `tweegobuild` , can you please add the **js only** and **css only**? thx before

**Comment by ChapelR** [comment]
Compiling both the CSS and JS doesn't take that much processing power. I'm not sure if separating them is worth it.

**Comment by arohman84** [comment]
oh ok, allright then. thx for the quick reply.

and how to compile and update the page but doesnt need to go new tab , its quite annoying when compile always open a new tab. thx before

**Comment by ChapelR** [comment]
In the `package.json` file under scripts, you'll see several scripts that look something like this:
```
"build": "gulp build && tweego -f $npm_package_config_format -m src/modules/ --head=src/head-content.html -o dist/index.html project && opn dist/index.html"
```
If you remove the final part (`&& opn dist/index.html`) from all of those scripts, or from the relevant ones, it will stop opening new tabs/windows in the browser.
