### ISSUE TITLE
csslint doesn' support CSS variables

### ISSUE THREAD

**Issue by zen14774** [ChapelR/tweego-setup#14]
First, thank you for creating this, it was extremely helpful.

Now my point:
I added some CSS variables to my code (the `var(--foo)` kind) and the linting started failing. I tried to find a solution but it looks like csslint just doesn't support them and it's not being regularly updated anymore. In the end I solved my problem by replacing csslint with stylelint. It was pretty straightforward (just install, add a settings file and tweak a couple lines in the gulp file) so I thought I'd leave a comment to give some feedback and say thanks.

Have a nice day!

**Comment by arohman84** [comment]
yep, me too i change the lint to stylelint + prettier, this combo is the best for my setup LOL

**Comment by ChapelR** [comment]
Thanks I'll look into it.

**Comment by tmedwards** [comment]
+1 for `stylelint`

**Comment by ChapelR** [comment]
I will probably just remove linting all together in v3, but if I don't I'll use stylelint.
