### ISSUE TITLE
tweego --watch flag needs explicit src/module to exist in order to watch

### ISSUE THREAD

**Issue by no-materials** [ChapelR/tweego-setup#15]
Greetings, not much of an issue but in order to achieve the `--watch` command from tweego, one must create an empty `src/modules` directory for it to watch,  since `src/modules` is explicitly passed as a modules argument to the tweego  build command in `package.json`.

**Comment by ChapelR** [comment]
Ah, there is a folder locally, I guess I need to put something in it for it to commit.
