### ISSUE TITLE
Story format change issue

### ISSUE THREAD

**Issue by darrenkearney** [ChapelR/tweego-setup#21]
I folks.

I tried using tweego-setup today. We're using the Harlowe 3 story format in our project. I tried using the npm config command, as well as running the format.bat file, and neither had any effect.

Steps to reproduce:
Attempt to change story format to harlowe-3.

Fix:
Manually update the format property to harlowe-3 in the package.json file.
```
  "config": {
    "format": "sugarcube-2"
  },
```
to
```
  "config": {
    "format": "harlowe-3"
  },
```

Credit where credit is due:
Thanks to Cyrus Firheir on the Twine discord server for the fix!

**Comment by ChapelR** [comment]
It seems to work for me just fine. Note that changing the config actually does **not** alter the the config as listed in your `package.json` file as those are actually just the defaults; in fact, I am surprised editing it changed the format at all. It's possible there is some error on my end, and I don't know with 100% certainty that NPM configs don't have weird limitations, so I'll continue exploring this on my end.

**Comment by darrenkearney** [comment]
Thanks. Yes, it did seem weird which is why I made the report.

I've since changed my project to use sugarcube story format, so I doubt I will be messing with harlowe configuration any further. If I encounter anything else I will let you know.

**Comment by ChapelR** [comment]
In v3 story formats will only be changed from the compiler options in the `StoryData` passage.
